import Head from 'next/head'
import header from '../components/header'
import footer from '../components/footer'
import '../styles/globals.css'

function App ({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>AppStore</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className="wrapper">
        <header />
        <Component {...pageProps} />
        <footer />
      </div>
    </>
  )
}

export default App
